apiVersion: v2
name: bentopdf
description: A Helm chart for BentoPDF - PDF manipulation service using BentoML
type: application
version: 1.1.0
appVersion: "2.1.0"
home: https://github.com/alam00000/bentopdf
icon: https://raw.githubusercontent.com/bentoml/BentoML/main/docs/source/_static/img/bentoml-icon.png
kubeVersion: ">=1.19.0-0"
keywords:
  - pdf
  - bentoml
  - converter
  - gotenberg
maintainers:
  - name: kriegalex
    email: kriegalex@gmail.com
sources:
  - https://github.com/alam00000/bentopdf
  - https://github.com/kriegalex/k8s-charts/tree/main/charts/bentopdf
deprecated: false
annotations:
  artifacthub.io/links: |
    - name: Chart source
      url: https://github.com/kriegalex/k8s-charts/tree/main/charts/bentopdf
    - name: Docker image source
      url: https://github.com/alam00000/bentopdf
  artifacthub.io/images: |
    - name: bentopdf
      image: ghcr.io/alam00000/bentopdf-simple:latest
